sudo: false
language: python
python:
  - "3.5"
  - "3.6"
env:
  - CY_INSIDE_TRAVIS=1
services:
  - postgresql
cache:
  pip: true
install:
  - python3 setup.py install
  - pip install flake8 codecov coverage
script:
  - flake8
  - coverage run setup.py test
after_success:
  - codecov
