sudo: false
language: python
python:
  - "3.5"
  - "3.6"
env:
  - CY_INSIDE_TRAVIS=1
services:
  - postgresql
addons:
  postgresql: "9.6"
cache:
  pip: true
install:
  - python3 setup.py install
  - pip install flake8 codecov coverage
before_script:
  - psql -c 'CREATE DATABASE "django-tally-test";' -U postgres
script:
  - flake8
  - coverage run setup.py test
after_success:
  - codecov
