# Generated by Django 2.0.7 on 2018-08-14 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_def', '0002_userdef_refactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDefTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.TextField()),
                ('template', models.TextField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='user_def.UserDefTemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
