# Generated by Django 2.0.7 on 2018-08-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='value',
            field=models.TextField(),
        ),
    ]
